# -*- coding: utf-8 -*-
"""depth_inference.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WiKKunKC8Mz6YSiYqCOMFqbHksOOtw4Q
"""

import os
from transformers import pipeline
from PIL import Image

# 1. 모델 로드
pipe = pipeline("depth-estimation", model="depth-anything/Depth-Anything-V2-Metric-Outdoor-Small-hf", device=0)

# 2. 현재 폴더 구조에 맞춘 경로 설정
input_folder = "my_images"
output_folder = "output_results"

if not os.path.exists(output_folder):
    os.makedirs(output_folder)

# 3. 폴더 안의 파일들 읽기
image_files = [f for f in os.listdir(input_folder) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]

print(f"📂 '{input_folder}'에서 {len(image_files)}장의 사진을 찾았습니다.")

for filename in image_files:
    img_path = os.path.join(input_folder, filename)
    image = Image.open(img_path)
    result = pipe(image)

    # 거리 추출
    depth_array = result['predicted_depth']
    center_dist = depth_array[depth_array.shape[0]//2, depth_array.shape[1]//2].item()

    # 결과 저장(Depth Map 시각화 결과물 + 픽셀별 깊이값)
    save_name = f"result_{center_dist:.2f}m_{filename}"
    save_path = os.path.join(output_folder, save_name)
    result['depth'].save(save_path)

    print(f"✅ {filename} 분석 완료: {center_dist:.2f}m")